// Dev quiz bank. Questions are grouped by category so players can drill into
// system design, full stack, general coding, or the web. Every question has a
// difficulty level (1 easy, 2 medium, 3 hard) that Easy/Normal/Hard modes
// filter on. Every run shuffles both the deck and each question's options, so
// the "correct" letter moves around and is never pinned to A. No hyphens, no
// duplicate questions, and draw questions never spell out their own answer.

export const QUIZ_CATEGORIES = [
    { id: "system-design", label: "System Design" },
    { id: "full-stack", label: "Full Stack" },
    { id: "coding", label: "Coding" },
    { id: "web", label: "Web & Internet" },
];

export const DIFFICULTIES = [
    { id: "easy", label: "Easy", timer: 30 },
    { id: "normal", label: "Normal", timer: 20 },
    { id: "hard", label: "Hard", timer: 12 },
];

// Question types:
//   mcq   -> pick one option (options + answer index)
//   tf    -> true or false (still re-shuffled so the letter moves)
//   fill  -> type the answer (answer: array of accepted, normalized ones)
//   order -> drag the steps into the right sequence (steps is the answer, answers keeps the correct order)
//   draw  -> place shapes from the tray onto the canvas and connect them (palette + edges is the answer)
export const POP_QUIZ = [
    // ---- System Design ----
    {
        category: "system-design",
        level: 3,
        type: "mcq",
        question: "Which pattern stops repeated calls to a failing dependency to prevent cascading failures?",
        options: ["Circuit breaker", "Observer", "Singleton", "Factory"],
        answer: 0,
    },
    {
        category: "system-design",
        level: 1,
        type: "mcq",
        question: "What is the main job of a load balancer?",
        options: [
            "Compiles source code",
            "Caches DNS records",
            "Distributes traffic across multiple servers",
            "Encrypts database queries",
        ],
        answer: 2,
    },
    {
        category: "system-design",
        level: 3,
        type: "mcq",
        question: "Which cache eviction policy removes the item not used for the longest time?",
        options: ["MRU", "LRU", "FIFO", "LFU"],
        answer: 1,
    },
    {
        category: "system-design",
        level: 1,
        type: "mcq",
        question: "Which in memory key value store is used for caching and pub/sub?",
        options: ["Elasticsearch", "SQLite", "PostgreSQL", "Redis"],
        answer: 3,
    },
    {
        category: "system-design",
        level: 1,
        type: "mcq",
        question: "What does horizontal scaling mean?",
        options: [
            "Upgrading one machine's CPU and RAM",
            "Adding more machines to share the load",
            "Splitting a monolith into folders",
            "Rewriting a service in a faster language",
        ],
        answer: 1,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "Where do messages go when a queue cannot deliver them after all retries?",
        options: ["Null stream", "Dead letter queue", "Trash topic", "Overflow bucket"],
        answer: 1,
    },
    {
        category: "system-design",
        level: 1,
        type: "mcq",
        question: "Which layer usually sits closest to the user to serve cached static content?",
        options: ["CDN", "Database replica", "Application server", "Message queue"],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What is the main reason to put a cache in front of a database?",
        options: [
            "To store backups of the schema",
            "To make the database read only",
            "To cut repeat read latency and DB load",
            "To replace the need for a load balancer",
        ],
        answer: 2,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "A queue between a web tier and worker tier exists mostly to handle what?",
        options: ["Traffic spikes without dropping work", "SQL compilation", "Client rendering", "DNS resolution"],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What does a health check let a load balancer do?",
        options: [
            "Take failing servers out of rotation",
            "Reboot the database automatically",
            "Cache static assets",
            "Encrypt traffic between servers",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "In cache aside, who writes the data into the cache?",
        options: [
            "The application, after a successful read from the store",
            "The database's replication log",
            "The CDN edge node",
            "The browser's service worker",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What does a cache do when a key is missing?",
        options: [
            "Falls through to the database and rewrites the cache",
            "Returns a random value",
            "Deletes the bucket",
            "Restarts the app server",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 1,
        type: "tf",
        question: "A dead letter queue stores messages that failed processing even after retries are exhausted.",
        answer: true,
    },
    {
        category: "system-design",
        level: 1,
        type: "tf",
        question: "Horizontal scaling means buying a bigger, stronger single machine.",
        answer: false,
    },
    {
        category: "system-design",
        level: 2,
        type: "tf",
        question: "In a typical load balanced setup, the load balancer is a single point of failure if nothing else is done.",
        answer: true,
    },
    {
        category: "system-design",
        level: 1,
        type: "tf",
        question: "A CDN mainly reduces latency by serving content from edge locations near the user.",
        answer: true,
    },
    {
        category: "system-design",
        level: 1,
        type: "fill",
        question: "A smart in memory data store famous for caching and queues, whose name starts with Re...",
        answer: ["redis"],
        hint: "Starts with Re",
    },
    {
        category: "system-design",
        level: 2,
        type: "fill",
        question: "A queue that receives a message which failed all retries is a dead letter ...",
        answer: ["queue", "q"],
        hint: "Type the word",
    },
    {
        category: "system-design",
        level: 2,
        type: "order",
        question: "Drag the cache aside read path into the correct order.",
        diagram: {
            nodes: [
                { id: "app", label: "App", x: 20, y: 50 },
                { id: "cache", label: "Cache", x: 55, y: 25 },
                { id: "db", label: "Database", x: 55, y: 78 },
            ],
            edges: [["app", "cache"], ["app", "db"]],
        },
        steps: [
            "App checks cache",
            "Cache miss, app reads DB",
            "App writes result into cache",
            "Return response to client",
        ],
    },
    {
        category: "system-design",
        level: 2,
        type: "order",
        question: "Drag the queue backed write path into the correct order.",
        diagram: {
            nodes: [
                { id: "client", label: "Client", x: 10, y: 50 },
                { id: "api", label: "API", x: 38, y: 30 },
                { id: "queue", label: "Queue", x: 38, y: 72 },
                { id: "worker", label: "Worker", x: 68, y: 50 },
                { id: "db", label: "Database", x: 88, y: 50 },
            ],
            edges: [["client", "api"], ["api", "queue"], ["queue", "worker"], ["worker", "db"]],
        },
        steps: [
            "Client sends request",
            "API pushes job to queue",
            "Worker pulls job from queue",
            "Worker processes and writes result",
            "Client gets confirmation",
        ],
    },
    {
        category: "system-design",
        level: 2,
        type: "order",
        question: "Drag the load balancing flow into the correct order.",
        diagram: {
            nodes: [
                { id: "client", label: "Client", x: 10, y: 50 },
                { id: "dns", label: "DNS", x: 35, y: 25 },
                { id: "lb", label: "Load balancer", x: 60, y: 50 },
                { id: "server", label: "Server", x: 85, y: 25 },
                { id: "db", label: "Database", x: 85, y: 78 },
            ],
            edges: [["client", "dns"], ["dns", "lb"], ["lb", "server"], ["server", "db"]],
        },
        steps: [
            "Client reaches DNS",
            "DNS returns LB address",
            "LB picks a healthy server",
            "Server handles the request",
            "LB routes reply back",
        ],
    },
    {
        category: "system-design",
        level: 3,
        type: "order",
        question: "Drag the caching strategy for a hot read heavy endpoint into the correct order.",
        steps: [
            "Identify the hot query",
            "Add cache in front of it",
            "Serve repeats from cache",
            "Evict and expire stale entries",
            "Invalidate on writes",
        ],
    },
    {
        category: "system-design",
        level: 1,
        type: "order",
        question: "Drag the architecture layers of a web app from the client side to storage.",
        diagram: {
            nodes: [
                { id: "client", label: "Client", x: 8, y: 50 },
                { id: "lb", label: "Load balancer", x: 33, y: 50 },
                { id: "app", label: "App tier", x: 58, y: 50 },
                { id: "db", label: "Data tier", x: 88, y: 50 },
            ],
            edges: [["client", "lb"], ["lb", "app"], ["app", "db"]],
        },
        steps: [
            "Client and browser",
            "Load balancer",
            "App tier",
            "Data tier and DB",
        ],
    },
    {
        category: "system-design",
        level: 3,
        type: "draw",
        question: "A shop app serves static assets from the edge, spreads API traffic across servers, and keeps data in one store. Drag the shapes you need onto the canvas and connect them.",
        palette: ["Client", "CDN", "Load Balancer", "API Servers", "Database", "Queue", "Cache"],
        edges: [["Client", "CDN"], ["CDN", "Load Balancer"], ["Load Balancer", "API Servers"], ["API Servers", "Database"]],
        annotations: [
            "CDN serves the static assets from edge locations near the user",
            "Load balancer spreads API traffic across the servers",
            "API servers read and write one shared database",
        ],
    },
    {
        category: "system-design",
        level: 2,
        type: "draw",
        question: "A photo site renders every view slowly. Add a fast lookup layer so repeat views skip the expensive work. Draw the architecture.",
        palette: ["Client", "App", "Cache", "Database"],
        edges: [["Client", "App"], ["App", "Cache"], ["App", "Database"]],
        annotations: [
            "App checks the cache first — repeat views are served instantly",
            "On a cache miss the app reads from the database",
            "App stores the rendered result back in the cache",
        ],
    },
    {
        category: "system-design",
        level: 2,
        type: "draw",
        question: "Uploads take a long time. Requests should come back fast while the heavy part happens later, and incoming jobs must never be dropped. Draw the flow.",
        palette: ["Client", "API", "Queue", "Worker", "Database"],
        edges: [["Client", "API"], ["API", "Queue"], ["Queue", "Worker"], ["Worker", "Database"]],
        annotations: [
            "API pushes the job to the queue and replies fast",
            "Queue holds every job — spikes never drop work",
            "Worker pulls jobs and does the heavy lifting",
            "Worker writes the finished result to the database",
        ],
    },
    {
        category: "system-design",
        level: 3,
        type: "draw",
        question: "Traffic grew and one instance can't keep up. Run the service twice and point both at one shared source of truth. Draw the architecture.",
        palette: ["Client", "Load Balancer", "Server", "Database"],
        edges: [
            ["Client", "Load Balancer"],
            ["Load Balancer", "Server"],
            ["Server", "Database"],
        ],
        annotations: [
            "Load balancer runs the service on two instances",
            "Both instances share one database — the single source of truth",
        ],
    },
    {
        category: "system-design",
        level: 3,
        type: "draw",
        question: "A rideshare app shows riders live driver locations over WebSocket, and profiles go through the API. Draw both flows starting from the load balancer.",
        palette: ["Client", "Load Balancer", "WebSocket Servers", "API Servers", "Redis Pub/Sub", "User Database"],
        edges: [
            ["Client", "Load Balancer"],
            ["Load Balancer", "WebSocket Servers"],
            ["Load Balancer", "API Servers"],
            ["WebSocket Servers", "Redis Pub/Sub"],
            ["API Servers", "User Database"],
        ],
        annotations: [
            "Load balancer routes riders to the WebSocket servers",
            "WebSocket servers push live driver locations via Redis Pub/Sub",
            "Load balancer routes profiles to the API servers",
            "API servers read and write the user database",
        ],
    },
    {
        category: "system-design",
        level: 1,
        type: "draw",
        question: "A blog serves static posts from a CDN at the edge and only hits the app server for dynamic comments. Draw the architecture.",
        palette: ["Client", "CDN", "App", "Database"],
        edges: [["Client", "CDN"], ["CDN", "App"], ["App", "Database"]],
        annotations: [
            "CDN serves the static posts from the edge",
            "App handles only the dynamic comments",
            "Comments are stored in the database",
        ],
    },
    {
        category: "system-design",
        level: 2,
        type: "draw",
        question: "A public API is being hammered by one client. Add a guard in front of the API that limits requests, then let the API reach the store. Draw it.",
        palette: ["Client", "Rate Limiter", "API", "Database"],
        edges: [["Client", "Rate Limiter"], ["Rate Limiter", "API"], ["API", "Database"]],
        annotations: [
            "Rate limiter caps requests per client",
            "API only serves the allowed traffic",
            "API reads and writes the database",
        ],
    },
    {
        category: "system-design",
        level: 1,
        type: "mcq",
        question: "Which is a benefit of microservices over a monolith?",
        options: ["Independent scaling and deploys", "Fewer moving parts to deploy", "One codebase to search", "No network calls between services"],
        answer: 0,
    },
    {
        category: "system-design",
        level: 1,
        type: "mcq",
        question: "Which statement about a CDN in front of an origin is true?",
        options: [
            "The origin only sees requests that miss the CDN cache",
            "The CDN replaces the database",
            "The CDN compiles the app code",
            "The CDN encrypts all traffic end to end",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 1,
        type: "tf",
        question: "Adding a read replica can improve read performance by spreading reads across more machines.",
        answer: true,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What is 'eventual consistency'?",
        options: [
            "Replicas converge to the same data over time, not instantly",
            "Data is always identical on every replica at all times",
            "Writes are rejected until a replica catches up",
            "The database never stores the same value twice",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What does 'idempotency' mean for an API?",
        options: [
            "Repeating the same request has the same effect as sending it once",
            "The request always returns the same response body",
            "The endpoint can only be called once",
            "The request is encrypted before sending",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What is a 'hot key' problem in a cache?",
        options: [
            "One key gets a disproportionate share of traffic and overloads a node",
            "A key that expires every few milliseconds",
            "A key stored on a server that is overheating",
            "Two keys that map to the same value",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "What does the CAP theorem state?",
        options: [
            "A distributed system can't guarantee all of consistency, availability and partition tolerance at once",
            "Every system must choose between caching and partitioning",
            "A database can only ever serve reads or writes",
            "Capacity always beats availability in a distributed system",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 2,
        type: "mcq",
        question: "Which is the best first move for handling a sudden traffic spike?",
        options: [
            "Auto scale servers and buffer the excess work in a queue",
            "Delete old database rows to free space",
            "Turn off the CDN so traffic hits the origin directly",
            "Rewrite the app in a faster language",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 3,
        type: "mcq",
        question: "What problem does a bloom filter solve?",
        options: [
            "Fast membership checks with a small chance of false positives",
            "Sorting large datasets in place",
            "Encrypting data at rest",
            "Guaranteeing exactly once delivery",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 3,
        type: "mcq",
        question: "What is the purpose of a write ahead log?",
        options: [
            "Durability — record the intended change before applying it",
            "Serving read queries faster",
            "Compressing stored data",
            "Balancing load across replicas",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 3,
        type: "mcq",
        question: "What is 'backpressure' in a streaming system?",
        options: [
            "Slowing the producer when the consumer can't keep up",
            "A firewall that blocks unwanted traffic",
            "Compressing messages before they are sent",
            "Retrying a failed request forever",
        ],
        answer: 0,
    },
    {
        category: "system-design",
        level: 3,
        type: "fill",
        question: "The model where replicas gradually match the latest write is called eventual ...",
        answer: ["consistency"],
        hint: "Type the word",
    },

    // ---- Full Stack ----
    {
        category: "full-stack",
        level: 1,
        type: "mcq",
        question: "What does REST stand for?",
        options: [
            "Representational State Transfer",
            "Remote Execution Service Toolkit",
            "Relational Entity Storage Type",
            "Rapid Endpoint Scaling Transport",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 1,
        type: "mcq",
        question: "Which HTTP method is idempotent and used to fully replace a resource?",
        options: ["POST", "PUT", "PATCH", "DELETE"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "Which HTTP header tells the client the format of the response body?",
        options: ["Accept Encoding", "User Agent", "Cache Control", "Content Type"],
        answer: 3,
    },
    {
        category: "full-stack",
        level: 1,
        type: "mcq",
        question: "Which HTTP status code means a resource was successfully created?",
        options: ["301", "201", "204", "418"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "What is a JSON Web Token (JWT)?",
        options: [
            "A database index type",
            "A CSS layout mode",
            "A signed token carrying claims",
            "A TLS certificate format",
        ],
        answer: 2,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "Which protocol upgrades HTTP to full duplex, real time comms?",
        options: ["SMTP", "WebSockets", "FTP", "GraphQL"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 3,
        type: "mcq",
        question: "When a frontend and an API are served from the same origin, which issue largely disappears?",
        options: ["XSS", "CORS", "SQL injection", "Cache invalidation"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "Which part of a JWT contains the actual claims (user id, role, exp)?",
        options: ["Payload", "Header", "Signature", "Cipher"],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 1,
        type: "tf",
        question: "PUT is idempotent. Sending the same PUT twice has the same effect as once.",
        answer: true,
    },
    {
        category: "full-stack",
        level: 2,
        type: "tf",
        question: "A JWT is encrypted by default, so anyone can read what's inside.",
        answer: false,
    },
    {
        category: "full-stack",
        level: 1,
        type: "tf",
        question: "WebSockets use the same request/response model as HTTP.",
        answer: false,
    },
    {
        category: "full-stack",
        level: 3,
        type: "fill",
        question: "The component that formats data to JSON on the way out and parses it on the way in is a serialization ...",
        answer: ["layer", "middleware"],
        hint: "Type the word",
    },
    {
        category: "full-stack",
        level: 1,
        type: "order",
        question: "Drag the full stack request round trip into the correct order.",
        diagram: {
            nodes: [
                { id: "browser", label: "Browser", x: 8, y: 50 },
                { id: "server", label: "Server", x: 38, y: 50 },
                { id: "db", label: "Database", x: 68, y: 50 },
                { id: "res", label: "Response", x: 92, y: 50 },
            ],
            edges: [["browser", "server"], ["server", "db"], ["server", "res"]],
        },
        steps: [
            "Browser sends request",
            "Server route matches",
            "Server queries data",
            "Server returns JSON",
            "Browser renders UI",
        ],
    },
    {
        category: "full-stack",
        level: 1,
        type: "mcq",
        question: "What's the difference between authentication and authorization?",
        options: [
            "Authentication proves who you are; authorization decides what you can do",
            "They are the same thing",
            "Authorization proves who you are; authentication decides what you can do",
            "Both only apply to passwords",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 1,
        type: "mcq",
        question: "Which HTTP method is NOT safe to retry automatically after a network timeout?",
        options: ["GET", "POST", "HEAD", "OPTIONS"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 1,
        type: "mcq",
        question: "Which status code should an API return when a client sends malformed JSON?",
        options: ["200", "400", "404", "500"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 1,
        type: "tf",
        question: "Authorization decides what a user can do; authentication verifies who they are.",
        answer: true,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "Which HTTP method should be used to update only a subset of fields?",
        options: ["PUT", "PATCH", "DELETE", "POST"],
        answer: 1,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "What does the SameSite cookie attribute help prevent?",
        options: ["CSRF", "SQL injection", "XSS", "Man in the middle"],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "Which statement about JWT vs server side sessions is true?",
        options: [
            "A JWT is stateless, so it scales horizontally without shared session storage",
            "A JWT always requires a database lookup on every request",
            "Server sessions can't be invalidated",
            "JWTs are stored only on the server",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "What does an OPTIONS preflight request check before a cross origin request?",
        options: [
            "Which methods and headers the server allows",
            "Whether the server is online",
            "The server's TLS certificate",
            "The server's database schema",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 2,
        type: "mcq",
        question: "Which is a valid reason to prefer server side rendering over a client rendered SPA?",
        options: [
            "Better SEO and faster first content",
            "No server needed at all",
            "It removes the need for a database",
            "It makes every API call faster",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 2,
        type: "fill",
        question: "The token scheme for an Authorization header that carries an access token is ...",
        answer: ["bearer"],
        hint: "Starts with B",
    },
    {
        category: "full-stack",
        level: 3,
        type: "mcq",
        question: "What does the Vary response header tell caches?",
        options: [
            "The response can differ based on a request header",
            "The response must never be cached",
            "The response changes on every request",
            "The server is overloaded",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 3,
        type: "mcq",
        question: "When a write must also update a cache, the safest approach is to...",
        options: [
            "Invalidate the cached key on write",
            "Ignore the cache entirely",
            "Write to the cache first, then the database",
            "Clear the whole cache on every request",
        ],
        answer: 0,
    },
    {
        category: "full-stack",
        level: 1,
        type: "fill",
        question: "The HTTP method that returns only the response headers and no body is ...",
        answer: ["head"],
        hint: "Type the method",
    },
    {
        category: "full-stack",
        level: 2,
        type: "fill",
        question: "A cross origin request with custom headers triggers a preflight ... request first.",
        answer: ["options"],
        hint: "Type the method",
    },
    {
        category: "full-stack",
        level: 2,
        type: "order",
        question: "Drag the JWT login flow into the correct order.",
        steps: [
            "Client sends credentials",
            "Server verifies and signs a JWT",
            "Client stores the token",
            "Client sends the token with each request",
            "Server validates the signature",
        ],
    },
    {
        category: "full-stack",
        level: 2,
        type: "order",
        question: "Drag the steps to add a new REST endpoint into the correct order.",
        steps: [
            "Define the route",
            "Validate the input",
            "Query or mutate data",
            "Return a status code",
            "Add tests",
        ],
    },

    // ---- General Coding ----
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "What is the time complexity of binary search on a sorted array?",
        options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
        answer: 1,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "Which data structure follows Last In First Out (LIFO)?",
        options: ["Stack", "Queue", "Heap", "Linked list"],
        answer: 0,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "In JavaScript, which keyword declares a variable that can't be reassigned?",
        options: ["let", "const", "var", "static"],
        answer: 1,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "What does the DRY principle stand for?",
        options: [
            "Don't Repeat Yourself",
            "Do Repeat Yourself",
            "Delete Rarely Used code",
            "Debug Recursively, Yes",
        ],
        answer: 0,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "Which Git command records the staged changes into history?",
        options: ["git add", "git commit", "git push", "git stash"],
        answer: 1,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "What is a pure function?",
        options: [
            "Same inputs always give same output, no side effects",
            "A function that only uses global state",
            "A function written in a single file",
            "A function that returns a random value",
        ],
        answer: 0,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "In an async function, which keyword pauses until the promise settles?",
        options: ["wait()", "yield", "await", "pause"],
        answer: 2,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "Which complexity class is the average case of Quicksort?",
        options: ["O(n)", "O(n log n)", "O(log n)", "O(n²)"],
        answer: 1,
    },
    {
        category: "coding",
        level: 3,
        type: "mcq",
        question: "Which technique turns an exponential recursive call into polynomial time by reusing past results?",
        options: ["Memoization", "Tree shaking", "Lazy loading", "Streaming"],
        answer: 0,
    },
    {
        category: "coding",
        level: 3,
        type: "mcq",
        question: "Why does binary search require a sorted array?",
        options: [
            "Each comparison can safely discard half the remaining range",
            "Hashing needs ordered keys",
            "To enable parallel reads",
            "So the compiler can vectorize the loop",
        ],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "tf",
        question: "Strings in JavaScript are immutable. replace() returns a new string.",
        answer: true,
    },
    {
        category: "coding",
        level: 1,
        type: "tf",
        question: "A queue is LIFO. The last item added is the first one out.",
        answer: false,
    },
    {
        category: "coding",
        level: 1,
        type: "tf",
        question: "A function that calls itself is recursive and needs a base case to stop.",
        answer: true,
    },
    {
        category: "coding",
        level: 1,
        type: "fill",
        question: "The complexity of binary search, in shorthand, is O ...",
        answer: ["logn"],
        hint: "Example: logn",
    },
    {
        category: "coding",
        level: 1,
        type: "order",
        question: "Drag the Git workflow into the correct order.",
        diagram: {
            nodes: [
                { id: "work", label: "Working dir", x: 10, y: 50 },
                { id: "stage", label: "Staging", x: 38, y: 50 },
                { id: "local", label: "Local repo", x: 66, y: 50 },
                { id: "remote", label: "Remote repo", x: 90, y: 50 },
            ],
            edges: [["work", "stage"], ["stage", "local"], ["local", "remote"]],
        },
        steps: [
            "git add",
            "git commit",
            "git push",
            "merge into main",
            "deploy",
        ],
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "What is the result of typeof null in JavaScript?",
        options: ["\"object\"", "\"null\"", "\"undefined\"", "\"number\""],
        answer: 0,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "What is the value of '5' + 3 in JavaScript?",
        options: ["\"53\"", "8", "\"8\"", "NaN"],
        answer: 0,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "What does the spread operator do in [...arr]?",
        options: ["Creates a shallow copy of arr", "Sorts arr in place", "Reverses arr", "Joins arr into a string"],
        answer: 0,
    },
    {
        category: "coding",
        level: 1,
        type: "mcq",
        question: "What does this print? console.log([1, 2, 3].map(n => n * 2).join('-'))",
        options: ["\"2-4-6\"", "\"123\"", "6", "\"1-2-3\""],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "What does this print? let x = 5; const f = () => x; x = 10; f();",
        options: ["10", "5", "undefined", "Error"],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "What does this print? console.log(0.1 + 0.2 === 0.3)",
        options: ["false", "true", "undefined", "NaN"],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "What does 'hoisting' mean for function declarations?",
        options: [
            "They are available before their definition line runs",
            "They are moved to a separate file",
            "They only work inside classes",
            "They are executed at the top of the file",
        ],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "Which data structure is best for a breadth first search of a graph?",
        options: ["Queue", "Stack", "Set", "Object"],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "mcq",
        question: "What is the time complexity of inserting at the front of a JavaScript array?",
        options: ["O(n)", "O(1)", "O(log n)", "O(n log n)"],
        answer: 0,
    },
    {
        category: "coding",
        level: 2,
        type: "fill",
        question: "The complexity of a hash map lookup on average, in shorthand, is O ...",
        answer: ["o1", "1"],
        hint: "Example: o1",
    },
    {
        category: "coding",
        level: 3,
        type: "mcq",
        question: "Which sorting algorithm is stable and O(n log n) in the worst case?",
        options: ["Merge sort", "Quicksort", "Selection sort", "Bubble sort"],
        answer: 0,
    },
    {
        category: "coding",
        level: 3,
        type: "mcq",
        question: "What is a race condition?",
        options: [
            "The outcome depends on the timing of concurrent operations",
            "Two functions with the same name",
            "A loop that never terminates",
            "A variable used before it is declared",
        ],
        answer: 0,
    },

    // ---- Web & Internet ----
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "What does DNS do?",
        options: [
            "Translates domain names into IP addresses",
            "Encrypts web traffic",
            "Serves HTML files",
            "Balances server load",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "Which HTTP status code means the resource was not found?",
        options: ["500", "404", "200", "401"],
        answer: 1,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "What does HTTPS add on top of HTTP?",
        options: ["Encryption via TLS", "Faster downloads", "Cookies by default", "Server side rendering"],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "Which HTTP method is typically used to send data to create a resource?",
        options: ["GET", "POST", "HEAD", "OPTIONS"],
        answer: 1,
    },
    {
        category: "web",
        level: 3,
        type: "mcq",
        question: "What does CORS stand for?",
        options: [
            "Cross Origin Resource Sharing",
            "Client Only Request Script",
            "Common Origin Routing System",
            "Content Origin Rate Setup",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "What is a browser cookie?",
        options: [
            "Small data the browser stores and sends with requests",
            "A cached copy of a page",
            "A JavaScript module",
            "A DNS record type",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 2,
        type: "mcq",
        question: "Which header tells shared caches whether a response may be cached?",
        options: ["Cache Control", "Content Type", "Accept", "Origin"],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "What is the standard port used for HTTPS?",
        options: ["80", "443", "8080", "53"],
        answer: 1,
    },
    {
        category: "web",
        level: 1,
        type: "tf",
        question: "A 301 redirect is permanent. A 302 is temporary.",
        answer: true,
    },
    {
        category: "web",
        level: 1,
        type: "tf",
        question: "Cookies are shared across all websites automatically.",
        answer: false,
    },
    {
        category: "web",
        level: 2,
        type: "tf",
        question: "GET requests are cached by browsers and CDNs by default.",
        answer: true,
    },
    {
        category: "web",
        level: 2,
        type: "order",
        question: "Drag the HTTPS connection setup into the correct order.",
        diagram: {
            nodes: [
                { id: "dns", label: "DNS", x: 12, y: 20 },
                { id: "client", label: "Client", x: 12, y: 80 },
                { id: "tls", label: "TLS handshake", x: 45, y: 50 },
                { id: "server", label: "Server", x: 75, y: 50 },
                { id: "http", label: "HTTP data", x: 92, y: 50 },
            ],
            edges: [["client", "dns"], ["client", "tls"], ["tls", "server"], ["server", "http"]],
        },
        steps: [
            "DNS lookup",
            "TCP connection",
            "TLS handshake",
            "Encrypted HTTP request",
            "Encrypted response",
        ],
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "A 503 status code means...",
        options: ["Service unavailable", "Not found", "Unauthorized", "Redirect"],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "Which protocol is used to send email?",
        options: ["SMTP", "FTP", "SSH", "WebSocket"],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "What does the browser do first when loading https://example.com?",
        options: ["DNS lookup", "Render the page", "Open a database", "Compile JavaScript"],
        answer: 0,
    },
    {
        category: "web",
        level: 1,
        type: "mcq",
        question: "What does 'cache busting' mean?",
        options: [
            "Changing the asset URL to force a fresh fetch",
            "Deleting the browser's history",
            "Blocking all cached content",
            "Encrypting cached files",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 2,
        type: "mcq",
        question: "What does the 'Cache-Control: no-cache' directive mean?",
        options: [
            "Revalidate the response before using a stored copy",
            "Never store anything in memory",
            "Cache it for one year",
            "Only cache on the server",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 2,
        type: "mcq",
        question: "What does Content Security Policy mainly help prevent?",
        options: ["XSS", "SQL injection", "DNS spoofing", "Phishing"],
        answer: 0,
    },
    {
        category: "web",
        level: 2,
        type: "mcq",
        question: "What is a 'reverse proxy'?",
        options: [
            "A server in front of app servers that forwards requests",
            "A proxy running on the client machine",
            "A database replica",
            "A browser extension",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 2,
        type: "mcq",
        question: "A 'mixed content' warning means...",
        options: [
            "An HTTPS page loaded an HTTP resource",
            "The page mixes HTML and CSS",
            "The server sent two content types",
            "The page is served from two origins",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 3,
        type: "mcq",
        question: "Which is true about HTTP/3?",
        options: ["It runs over QUIC on UDP", "It requires a new TCP port", "It removes TLS", "It only works over WebSocket"],
        answer: 0,
    },
    {
        category: "web",
        level: 3,
        type: "mcq",
        question: "What does the Strict Transport Security header do?",
        options: [
            "Forces the browser to use HTTPS for the domain",
            "Blocks all redirects",
            "Disables cookies",
            "Speeds up DNS lookups",
        ],
        answer: 0,
    },
    {
        category: "web",
        level: 3,
        type: "tf",
        question: "DNS records are eventually consistent across the globe.",
        answer: true,
    },
    {
        category: "web",
        level: 2,
        type: "fill",
        question: "The header that tells a browser which origin may read the response is Access-Control-Allow-...",
        answer: ["origin"],
        hint: "Type the word",
    },
    {
        category: "web",
        level: 1,
        type: "fill",
        question: "The three letter protocol that maps a domain name to an IP address is ...",
        answer: ["dns"],
        hint: "Type the acronym",
    },
    {
        category: "web",
        level: 1,
        type: "fill",
        question: "The default port number for plain HTTP is ...",
        answer: ["80"],
        hint: "Type the number",
    },
    {
        category: "web",
        level: 2,
        type: "order",
        question: "Drag the steps of a cache miss into the correct order.",
        steps: [
            "Browser checks its cache",
            "Cache entry is stale or missing",
            "Browser sends the request",
            "Server responds with cache headers",
            "Browser stores the fresh copy",
        ],
    },
    {
        category: "web",
        level: 2,
        type: "order",
        question: "Drag the steps of a DNS lookup into the correct order.",
        steps: [
            "Browser checks its own cache",
            "Query goes to the recursive resolver",
            "Resolver asks the root and TLD servers",
            "Authoritative server returns the IP",
            "Browser connects to the IP",
        ],
    },
];

export const shuffleDeck = (items) => {
    const deck = [...items];
    for (let i = deck.length - 1; i > 0; i -= 1) {
        const j = Math.floor(Math.random() * (i + 1));
        [deck[i], deck[j]] = [deck[j], deck[i]];
    }
    return deck;
};

// Pool filtered by category and difficulty level. Easy only asks level 1,
// Normal takes 1 and 2, Hard only asks the level 3 brain teasers.
export const quizPool = (category, difficulty) => {
    const byCategory = category === "all" ? POP_QUIZ : POP_QUIZ.filter((q) => q.category === category);
    let pool = byCategory;
    if (difficulty === "easy") pool = byCategory.filter((q) => (q.level || 2) === 1);
    else if (difficulty === "hard") pool = byCategory.filter((q) => (q.level || 2) === 3);
    else pool = byCategory.filter((q) => (q.level || 2) <= 2);
    // A category may have no questions at the chosen tier. Fall back to the
    // full category deck instead of starting an empty quiz.
    return pool.length ? pool : byCategory;
};

// Prepare a question for play:
//  - mcq/tf: shuffle options, reassign answer index so it's never stuck at A
//  - order:  shuffle steps so the player has to drag them around
//  - fill:   normalize accepted answers for forgiving matching
//  - draw:   nothing to shuffle; the edges are the answer
export const prepareQuestion = (q) => {
    if (q.type === "mcq" || q.type === "tf") {
        const isTf = q.type === "tf";
        const options = isTf ? shuffleDeck(["True", "False"]) : shuffleDeck(q.options);
        const correctText = isTf ? (q.answer ? "True" : "False") : q.options[q.answer];
        return { ...q, options, answer: options.indexOf(correctText) };
    }
    if (q.type === "order") {
        return { ...q, steps: shuffleDeck([...q.steps]), answers: [...q.steps] };
    }
    if (q.type === "fill") {
        const norm = (s) => s.trim().toLowerCase().replace(/[\s.'"-]+/g, "");
        return { ...q, answers: q.answer.map(norm) };
    }
    return q;
};